// import { getShoes } from "@/lib/api";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";

export default function HomePage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto w-[90%] mt-5 mb-5">
				<div>
					<Link href={"/collections"}>
						<img src="images/hero.jpeg" alt="Hero Image" />
					</Link>
					<h4 className="text-xl font-bold uppercase mt-2">classics for a reason</h4>

					<div className="flex text-sm font-medium flex-wrap gap-2 mt-4">
						<a href="/collections" className="py-2 px-5 bg-black text-white  rounded-full">
							Shop All
						</a>
						<a href="/men" className="py-2 px-5 bg-black text-white  rounded-full">
							Shop Mens
						</a>
						<a href="/women" className="py-2 px-5 bg-black text-white  rounded-full">
							Shop Womens
						</a>
					</div>
				</div>
				<div className="mt-6">
					<h4 className="text-lg font-semibold">Trending Right Now</h4>
				</div>

				<h3 className="text-2xl mt-5 font-medium mb-4">Sneakers Membership</h3>
				<div className="bg-[#111] text-white px-4 pt-2 pb-4">
					<h4 className="text-xl font-bold uppercase mt-5 ">Become a Sneaker Head</h4>
					<span className="block text-sm mt-2">Sign up for free. Join the community.</span>
					<a
						href="/login"
						className="py-2 px-5 mt-4 inline-block bg-white rounded-full text-gray-900">
						Join Us
					</a>
				</div>
			</div>
		</>
	);
}
